---
- name: install ansible required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - MySQL-python
    - python-docker-py
    - python-pip
    - policycoreutils-python

- name: install python pip modules
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - zabbix-api
